### PR TITLE
renamed bandwidths to band_wavelengths

### LINKED ISSUE #6: Optical Filter should specify 2-wavelength passband
The optical filters from doric lenses don't really have a peak wavelength, but rather a flat pass band. See figure 3.1 [here](https://doriclenses.com/downloads/UserManual/UserManual_ilFMC_GEN3_V1.0.0.pdf).

So, instead of peak_wavelength and bandwidth, we should specify a 2-wavelength passband ex.  
```python
emission_filter = OpticalFilter(
            name="emission_filter",
            description="...",
            manufacturer="Doric Lenses",
            model="4 ports Fluorescence Mini Cube - GCaMP",
            pass_band_in_nm=(460.0, 490.0)
            filter_type="bandpass",
        )
```

### PR DESCRIPTION
**Pull request by pauladkisson**
Fixes #6

### CODE REVIEW

**Comment by pauladkisson** [comment]
@alessandratrapani, continuing the conversation here.
>  I agree pass_band_in_nm is a better name for that. However I don't think we should remove the peak_wavelength, usually filters are reported as wavelength/bandwidth, eg. 920/30 nm where the 30 nm large bandwidth is centered at 920. Maybe we can change the name in central_wavelength or something like this, but still keep this information

I found this [resource](https://www.edmundoptics.com/knowledge-center/application-notes/optics/optical-filters/) from edmund optics that goes through most of the relevant terms.

I think we should be careful to avoid conflating the peak transmittance wavelength with the central wavelength, which can be different (see Figure 1). So, we can keep the peak transmittance wavelength as an optional attribute but we just need to make it clear that it's not the same as the central wavelength.

The way I see it we can choose between a center wavelength + bandwidth representation (ex. 920±30nm) or a band wavelengths representation (ex. [890nm, 950nm]). But, we shouldn't have both because they describe the same thing. I think they both work pretty well for bandpass filters and bandstop (aka notch) filters, but the band wavelengths representation seems a little less awkward for longpass filters and shortpass filters.

What do you think? Am I missing anything here?

**Comment by alessandratrapani** [comment]
> The way I see it we can choose between a center wavelength + bandwidth representation (ex. 920±30nm) or a band wavelengths representation (ex. [890nm, 950nm]). But, we shouldn't have both because they describe the same thing.

I agree with this; I think experimenters are more used to the center wavelength + bandwidth representation, while datasheets from the manufacturer report also band wavelengths. 

>Maybe the best solution is to simply have different Device objects for each of the four different types of filters: BandPassOpticalFilter, BandStopOpticalFilter, LongPassOpticalFilter, ShortPassOpticalFilter. That way we can describe each filter naturally: Center wave length and bandwidth for BandPassOpticalFilter and BandStopOpticalFilter; cutoff wavelength and slope for LongPassOpticalFilter and ShortPassOpticalFilter.

I think it might be a little too far, but also a simpler way to handle this case. @weiglszonja @luiztauffer, what do you guys think?

**Comment by weiglszonja** [comment]
> > Maybe the best solution is to simply have different Device objects for each of the four different types of filters: BandPassOpticalFilter, BandStopOpticalFilter, LongPassOpticalFilter, ShortPassOpticalFilter. That way we can describe each filter naturally: Center wave length and bandwidth for BandPassOpticalFilter and BandStopOpticalFilter; cutoff wavelength and slope for LongPassOpticalFilter and ShortPassOpticalFilter.
> 
> I think it might be a little too far, but also a simpler way to handle this case. @weiglszonja @luiztauffer, what do you guys think?

I think it's fine to have dedicated filter objects, I might merge `BandPassOpticalFilter` and `BandStopOpticalFilter` they could be distinguished by (for instance) `band_filter_type  = ["band-pass", "band-stop"]` required attribute:

```python

band_pass_filter = BandOpticalFilter(
    band_filter_type='band-pass',  # or 'band-stop'
    center_wavelength=650,
    bandwidth=20,
)

long_pass_filter = EdgeOpticalFilter(
    edge_filter_type='long-pass', # or short-pass
    cutoff_wavelength=600,
    slope=0.5
)
```

Would it make sense to have an additional attribute for each filter that could describe whether it was used for excitation/emission?

**Comment by pauladkisson** [comment]
> Would it make sense to have an additional attribute for each filter that could describe whether it was used for excitation/emission?

I don't think so bc the FiberPhotometryTable already references the filters as `excitation_filter` and `emission_filter`, so that information is already present at the table-level

**Comment by weiglszonja** [comment]
> > Would it make sense to have an additional attribute for each filter that could describe whether it was used for excitation/emission?
> 
> I don't think so bc the FiberPhotometryTable already references the filters as `excitation_filter` and `emission_filter`, so that information is already present at the table-level

Ah right, that seems reasonable.

**Comment by pauladkisson** [comment]
`BandOpticalFilter` and `EdgeOpticalFilter` sound good to me tho!

**Review by weiglszonja — APPROVED** [review]
Looks good! Thanks @pauladkisson

**Pull request merged**
